on:
  push:
    branches:
      - 'main'
jobs:
  build-validate:
    runs-on: ubuntu-latest
    name: Production Push
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Script
        id: runscript
        run: ./entrypoint.sh
        with:
          realm: ${{ secrets.REALM }}
          token_id: ${{ secrets.TOKEN_ID }}
          token_secret: ${{ secrets.TOKEN_SECRET }}
          branch: ${{ github.ref_name	}}