on:
  push:
    branches:
      - 'main'
jobs:
  build-validate:
    runs-on: ubuntu-latest
    name: Production Push
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install JDK
        uses: actions/setup-java@v2
        with: 
          distribution: 'zulu'
          java-version: '11'

      - name: Install SDF
        run: |
          npm install -g @oracle/suitecloud-cli

      - name: Push to Account
        run: |
          cd /usr/local/lib/node_modules/@oracle/suitecloud-cli
          npm install
          cd "/github/workspace"
          suitecloud account:savetoken --account ${{secrets.REALM}} --authid helloWorld --tokenid ${{secrets.TOKEN_ID}} --tokensecret ${{secrets.TOKEN_SECRET}}
