on:
  push:
    branches:
      - 'main'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Production Push
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Hello world action step
        id: hello
        uses: ./entrypoint.sh
        with:
          realm: ${{ secrets.REALM }}
          token_id: ${{ secrets.TOKEN_ID }}
          token_secret: ${{ secrets.TOKEN_SECRET }}
      # Use the output from the `hello` step
      - name: Extra Step
        run: echo "Test"
      - name: Hello world action step
        uses: MikeMeeseeks/helloActionsNs@sandbox
      - name: Extra Step 2
        run: echo "Test 2"