on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

  validate:
    runs-on: ubuntu-latest
    name: validate
    needs: [build]
    steps:
      - name: Shell Script
        id: shell
        uses: MikeMeeseeks/helloActionsNs@main
        with:
          realm: ${{ secrets.REALM }}
          token_id: ${{ secrets.TOKEN_ID }}
          token_secret: ${{ secrets.TOKEN_SECRET }}
          branch: ${{ github.ref_name	}}